# Generated by Django 4.2.14 on 2024-08-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
    ]
