# Generated by Django 4.2.14 on 2024-08-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'post')},
        ),
    ]
