# Generated by Django 4.2.14 on 2024-08-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
    ]
